---
version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nomad_db
      POSTGRES_USER: nomad_user
      POSTGRES_PASSWORD: nomad_password
    ports:
      - 5432:5432
volumes:
  postgres_data: null
