# Generated by Django 4.2.16 on 2024-10-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="deadline",
        ),
    ]
