# Generated by Django 4.2.16 on 2024-10-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_jobseeker_first_name_jobseeker_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
